// Concatenates src/theme/*.css into themes/pokecut.css, the single file BB
// loads through `bb.themes`. Theme CSS is BB's only app-wide stylesheet that
// lives exactly as long as the theme is selected, so the chat layer ships in it
// too. Run on every build; `--check` fails when the committed file is stale.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const PARTS = ["base.css", "chat.css", "integrations.css"];
const MAX_BYTES = 256_000; // BB's CUSTOM_THEME_CSS_MAX_LENGTH

const header =
  "/* GENERATED by scripts/build-theme.mjs from src/theme/" +
  PARTS.join(", src/theme/") +
  ". Edit the sources, not this file. */\n\n";
const css = header + PARTS.map((name) => readFileSync(join(root, "src/theme", name), "utf8").trimEnd()).join("\n\n") + "\n";

if (Buffer.byteLength(css) > MAX_BYTES) throw new Error(`theme CSS is ${Buffer.byteLength(css)} bytes, over BB's ${MAX_BYTES}`);

const target = join(root, "themes/pokecut.css");
if (process.argv.includes("--check")) {
  let current = "";
  try { current = readFileSync(target, "utf8"); } catch {}
  if (current !== css) { console.error("themes/pokecut.css is stale; run npm run build:theme"); process.exit(1); }
} else {
  writeFileSync(target, css);
  console.log(`themes/pokecut.css ${Buffer.byteLength(css)} bytes`);
}
